### ISSUE TITLE
Comparing fields in a case-insensitive manner

### ISSUE THREAD

**Issue by Alex3837** [mkfl3x/json-delta#1]
It would be cool to add a feature to the comparator with the ability to check the value of fields in a case-insensitive way. It often happens that the response comes with a field that is similar to the expected one, but has a different case than the actual one, for example: **_Github_** and **_GitHub_**. In this case, our check will fall, although a different register is not critical for us when comparing.

**Comment by mkfl3x** [comment]
Thanks for request. Feature is added. Please check is that fit for your purposes

**Comment by Alex3837** [comment]
Exactly what is needed, thanks!)
