### ISSUE TITLE
Getting NoSuchMethodError

### ISSUE THREAD

**Issue by rishibhushan** [mkfl3x/json-delta#2]
This is what I did in Java
```
JsonDelta jsonDelta = new JsonDelta();
JsonDeltaReport report = jsonDelta.compare("{\"a\":1}","{\"a\":1}");
System.out.println(report);
```
But I'm getting error

> java.lang.NoSuchMethodError: 'java.util.Map com.google.gson.JsonObject.asMap()'
> 
> 	at org.mkfl3x.jsondelta.JsonDelta.compareObjects(JsonDelta.kt:62)
> 	at org.mkfl3x.jsondelta.JsonDelta.comparisonResolver(JsonDelta.kt:48)
> 	at org.mkfl3x.jsondelta.JsonDelta.compare(JsonDelta.kt:38)
> 	at framework.Test.compare(Test.java:69)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
> 	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
> 	at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
> 	at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
> 	at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
> 	at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
> 	at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
> 	at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
> 	at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
> 	at org.testng.TestRunner.privateRun(TestRunner.java:808)
> 	at org.testng.TestRunner.run(TestRunner.java:603)
> 	at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
> 	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
> 	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
> 	at org.testng.SuiteRunner.run(SuiteRunner.java:326)
> 	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
> 	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
> 	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
> 	at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
> 	at org.testng.TestNG.runSuites(TestNG.java:1092)
> 	at org.testng.TestNG.run(TestNG.java:1060)
> 	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
> 	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)

**Comment by mkfl3x** [comment]
Hello! Could you please give me a bit more context? Which Java you did use? 
(For me this code works fine)

**Comment by rishibhushan** [comment]
Hi, 
Thanks for replying.

I used Java 17 (java version "17.0.4").
But since you asked. I'll try with Java 8, 11 to see if there is any difference.

**Comment by mkfl3x** [comment]
Could you please run the same code in clean project?
Looks like it's environment problem - I tried few times and can't reproduce it
